# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "$all$username$sudo$character"

right_format = "$status$cmd_duration$git_metrics"

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "â‹ˆâ”ˆ"
disabled = false

[username]
format = "[$user]($style) "
show_always = true

[status]
disabled = false

# [character]
# success_symbol = "[â¯](bold green)"
# error_symbol = "[âœ–](bold red)"

[battery]
disabled = true
format = "([$symbol$percentage ]($style))"
full_symbol = "ó°¹ "
charging_symbol = "[ó°‚„ ](italic bold green)"
discharging_symbol = "ó°½ "
unknown_symbol = "ó°½ "
empty_symbol = "ó°‚ "

[[battery.display]]
threshold = 30
style = "italic bold red"
discharging_symbol = "ó°‚ƒ "

[[battery.display]]
threshold = 60
style = "italic dimmed bright-purple"

[[battery.display]]
threshold = 70
style = "italic dimmed yellow"

[aws]
symbol = "îŒ½  "
disabled = true

[bun]
format = "via [$symbol]($style)"

[buf]
format = "via [$symbol]($style)"
symbol = "ï’ "

[c]
format = "via [$symbol(-$name)]($style)"
symbol = "î˜ "

[cmake]
format = "via [$symbol]($style)"
symbol = "î” "

[cobol]
format = "via [$symbol]($style)"

[conda]
format = "via [$symbol$environment]($style)"
symbol = "ï„Œ "

[crystal]
format = "via [$symbol]($style)"
symbol = "î˜¯ "

[daml]
format = "via [$symbol]($style)"

[dart]
format = "via [$symbol]($style)"
symbol = "î˜ "

[deno]
format = "via [$symbol]($style)"

[directory]
read_only = " ó°Œ¾"

[docker_context]
symbol = "ïŒˆ "

[dotnet]
format = "via [$symbol(ğŸ¯ $tfm )]($style)"

[elixir]
format = "via [$symbol]($style)"
symbol = "î˜­ "

[elm]
format = "via [$symbol]($style)"
symbol = "î˜¬ "

[erlang]
format = "via [$symbol]($style)"

[fennel]
format = "via [$symbol]($style)"
symbol = "îš¯ "

[fossil_branch]
symbol = "ï˜ "

[git_branch]
symbol = "ï˜ "

[git_commit]
tag_symbol = ' ï’ '

[git_metrics]
format = "([+$added]($added_style) )([-$deleted]($deleted_style) )"
disabled = false

[gleam]
format = "via [$symbol]($style)"

[golang]
format = "via [$symbol]($style)"
symbol = "î˜§ "

[guix_shell]
format = "via [$symbol]($style)"
symbol = "ïŒ¥ "

[gradle]
format = "via [$symbol]($style)"
symbol = "î™  "

[haskell]
format = "via [$symbol]($style)"
symbol = "î· "

[haxe]
format = "via [$symbol]($style)"
symbol = "î™¦ "

[helm]
format = "via [$symbol]($style)"

[hg_branch]
symbol = "ï˜ "

[hostname]
ssh_symbol = "î¬ "

[java]
format = "via [$symbol]($style)"
symbol = "î‰– "

[julia]
format = "via [$symbol]($style)"
symbol = "î˜¤ "

[kotlin]
format = "via [$symbol]($style)"
symbol = "î˜´ "

[lua]
format = "via [$symbol]($style)"
symbol = "î˜  "

[memory_usage]
symbol = "ó°› "

[meson]
format = "via [$symbol]($style)"
symbol = "ó°”· "

[mojo]
format = "via [$symbol]($style)"

[nim]
format = "via [$symbol]($style)"
symbol = "ó°†¥ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
format = "via [$symbol]($style)"
symbol = "îœ˜ "

[ocaml]
format = '(via [$symbol(\($switch_indicator$switch_name\))]($style))'
symbol = "î™º "

[opa]
format = "via [$symbol]($style)"

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

[package]
symbol = "ó°— "

[perl]
format = "via [$symbol]($style)"
symbol = "î™¾ "

[php]
format = "via [$symbol]($style)"
symbol = "î˜ˆ "

[pijul_channel]
symbol = "ï˜ "

[pulumi]
format = "via [$symbol$stack]($style)"

[purescript]
format = "via [$symbol]($style)"

[python]
format = "via [$symbol]($style)"
symbol = "îˆµ "

[quarto]
format = "via [$symbol]($style)"

[raku]
format = "via [$symbol]($style)"

[red]
format = "via [$symbol]($style)"

[rlang]
format = "via [$symbol]($style)"
symbol = "ó°Ÿ” "

[ruby]
format = "via [$symbol]($style)"
symbol = "î‘ "

[rust]
format = "via [$symbol]($style)"
symbol = "ó±˜— "

[scala]
format = "via [$symbol]($style)"
symbol = "îœ· "

[solidity]
format = "via [$symbol]($style)"

[swift]
format = "via [$symbol]($style)"
symbol = "î• "

[typst]
format = "via [$symbol]($style)"

[vagrant]
format = "via [$symbol]($style)"

[vlang]
format = "via [$symbol]($style)"

[zig]
format = "via [$symbol]($style)"
symbol = "îš© "

